root: http://philipwalton.com
devroot: http://192.168.1.118
permalink: /articles/:title
auto: true
server: false
markdown: rdiscount
pygments: true

# Vendor Settings
google_analytics_tracking_id: UA-21292978-1
disqus_shortname: philipwalton