permalink: /articles/:title

# Use the port config option to determine if we're in prod or dev
# anything other than port 80 is assumed to be dev
port: 80
url: http://philipwalton.com

markdown: rdiscount
pygments: true
paginate: 6


exclude:
- config.rb
- README.md
- Rakefile
- components

# Vendor Settings
google_analytics_tracking_id: UA-21292978-1
disqus_shortname: philipwalton
