root: http://philipwalton.com
devroot: http://localhost
permalink: /articles/:title
auto: true
server: false
markdown: rdiscount
pygments: true
exclude:
- config.rb
- README.md
- Rakefile

# Vendor Settings
google_analytics_tracking_id: UA-21292978-1
disqus_shortname: philipwalton